/**
 * 安装向导 - 主安装 API
 * POST /api/install
 */

import { NextRequest, NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import { promises as fs } from 'fs';

const execAsync = promisify(exec);

export async function POST(request: NextRequest) {
  try {
    const config = await request.json();
    
    // 1. 生成环境变量文件
    const envContent = generateEnvFile(config);
    await fs.writeFile('.env', envContent);
    
    // 2. 安装依赖
    console.log('安装依赖...');
    await execAsync('pnpm install');
    
    // 3. 运行数据库迁移
    console.log('运行数据库迁移...');
    await execAsync('pnpm prisma migrate deploy');
    
    // 4. 生成 Prisma Client
    console.log('生成 Prisma Client...');
    await execAsync('pnpm prisma generate');
    
    // 5. 创建管理员账户
    console.log('创建管理员账户...');
    const { PrismaClient } = await import('@prisma/client');
    const prisma = new PrismaClient();
    
    // 生成密码哈希
    const bcrypt = await import('bcrypt');
    const passwordHash = await bcrypt.hash(config.adminPassword, 14);
    
    // 创建管理员用户
    await prisma.user.create({
      data: {
        username: config.adminUsername,
        email: config.adminEmail,
        passwordHash,
        role: 'ADMIN',
        isVerified: true,
      },
    });
    
    await prisma.$disconnect();
    
    // 6. 创建安装标记文件
    await fs.writeFile('.installed', new Date().toISOString());
    
    return NextResponse.json({
      success: true,
      message: '安装成功',
    });
  } catch (error) {
    console.error('安装失败:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : '安装失败',
      },
      { status: 500 }
    );
  }
}

function generateEnvFile(config: any): string {
  const lines = [
    '# CMAMSys Environment Configuration',
    '# Generated by Install Wizard',
    '',
    '# Database',
    `DATABASE_URL="postgresql://${config.databaseUser || 'postgres'}:${config.databasePassword || ''}@${config.databaseHost || 'localhost'}:${config.databasePort || 5432}/${config.databaseName || 'cmamsys'}"`,
    '',
    '# Authentication',
    `JWT_SECRET="${config.jwtSecret}"`,
    `JWT_ACCESS_TOKEN_EXPIRY="15m"`,
    `JWT_REFRESH_TOKEN_EXPIRY="7d"`,
    `REFRESH_TOKEN_SECRET="${config.refreshTokenSecret}"`,
    '',
    '# Encryption',
    `ENCRYPTION_KEY="${config.encryptionKey}"`,
    '',
    '# Security',
    `CSRF_SECRET="${config.csrfSecret}"`,
    `BCRYPT_ROUNDS="14"`,
    `MAX_LOGIN_ATTEMPTS="5"`,
    `LOCKOUT_DURATION_MS="900000"`,
    '',
    '# Session',
    `SESSION_SECRET="${config.sessionSecret}"`,
    `SESSION_MAX_AGE=604800000`,
    '',
    '# Application',
    `APP_NAME="${config.appName}"`,
    `APP_URL="${config.appUrl}"`,
    `APP_PORT="${config.appPort}"`,
    `NODE_ENV="production"`,
    '',
    '# Redis',
    `REDIS_URL="${config.enableRedis ? config.redisUrl : ''}"`,
    '',
    '# Email Configuration',
    `SMTP_ENABLED="${config.enableEmail}"`,
    `SMTP_HOST="${config.enableEmail ? config.smtpHost : ''}"`,
    `SMTP_PORT="${config.enableEmail ? config.smtpPort : ''}"`,
    `SMTP_SECURE="${config.enableEmail ? config.smtpSecure : ''}"`,
    `SMTP_USER="${config.enableEmail ? config.smtpUser : ''}"`,
    `SMTP_PASSWORD="${config.enableEmail ? config.smtpPassword : ''}"`,
    `SMTP_FROM="${config.enableEmail ? config.smtpFrom : ''}"`,
    `SMTP_FROM_NAME="${config.enableEmail ? config.smtpFromName : ''}"`,
    '',
    '# Monitoring',
    `SENTRY_DSN="${config.enableSentry ? config.sentryDsn : ''}"`,
    '',
    '# API Versioning',
    `API_DEFAULT_VERSION="v1"`,
    '',
    '# CORS',
    `ALLOWED_ORIGINS="${config.appUrl}"`,
    `ALLOWED_METHODS="GET,POST,PUT,DELETE,PATCH,OPTIONS"`,
    `ALLOWED_HEADERS="Content-Type,Authorization,X-CSRF-Token"`,
    '',
    '# Upload',
    `MAX_FILE_SIZE=10485760`,
    `ALLOWED_FILE_TYPES=".pdf,.doc,.docx,.txt,.csv,.xlsx,.xls,.png,.jpg,.jpeg,.gif"`,
    '',
    '# Paths',
    `INSTALL_PATH="${config.installPath || './'}"`,
    `DATA_PATH="${config.dataPath || './data'}"`,
    `LOG_PATH="${config.logPath || './logs'}"`,
    `UPLOAD_PATH="${config.uploadPath || './uploads'}"`,
    `TEMP_PATH="${config.tempPath || './temp'}"`,
  ];
  
  return lines.join('\n');
}
