#!/bin/bash

# API 使用历史检查脚本
# 检查哪些 API 可能已经被使用过

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  API 使用历史检查                                          ║"
echo "║  检查哪些 API 可能已经被使用过                             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 需要检查的 API 服务：${NC}"
echo ""

# AI 服务列表
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${RED}🔴 AI Services（最高优先级）${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. DeepSeek AI"
echo "   控制台: https://platform.deepseek.com/"
echo "   检查项:"
echo "   - [ ] 查看 API Keys 列表"
echo "   - [ ] 检查 API 调用记录"
echo "   - [ ] 查看费用统计"
echo "   - [ ] 如果有使用记录，立即撤销旧 Key"
echo ""

echo "2. VolcEngine AI (火山引擎)"
echo "   控制台: https://console.volcengine.com/"
echo "   检查项:"
echo "   - [ ] 查看 API Keys 列表"
echo "   - [ ] 检查调用日志"
echo "   - [ ] 查看 QPS 使用情况"
echo "   - [ ] 查看费用明细"
echo "   - [ ] 如果有使用记录，立即撤销旧 Key"
echo ""

echo "3. Aliyun AI (阿里云)"
echo "   控制台: https://www.aliyun.com/"
echo "   检查项:"
echo "   - [ ] 查看 AccessKey 管理"
echo "   - [ ] 检查调用日志"
echo "   - [ ] 查看 API 使用量"
echo "   - [ ] 查看费用统计"
echo "   - [ ] 如果有使用记录，立即禁用旧 Key"
echo ""

echo "4. OpenAI"
echo "   控制台: https://platform.openai.com/"
echo "   检查项:"
echo "   - [ ] 查看 API Keys"
echo "   - [ ] 检查 Usage 记录"
echo "   - [ ] 查看费用统计"
echo "   - [ ] 如果有使用记录，立即撤销旧 Key"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${YELLOW}🟠 Storage（高风险）${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5. AWS S3"
echo "   控制台: https://console.aws.amazon.com/"
echo "   检查项:"
echo "   - [ ] 查看 IAM 用户"
echo "   - [ ] 检查 Access Keys"
echo "   - [ ] 查看 S3 访问日志"
echo "   - [ ] 查看 CloudTrail 日志"
echo "   - [ ] 如果有异常访问，立即撤销 Access Keys"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${YELLOW}🟡 其他服务（中等优先级）${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6. Bilibili"
echo "   控制台: https://www.bilibili.com/"
echo "   检查项:"
echo "   - [ ] 如果使用了 Bilibili API，检查使用记录"
echo "   - [ ] 如果有问题，清除 Cookie 并重新生成"
echo ""

echo "7. SMTP 邮件服务"
echo "   检查项:"
echo "   - [ ] 如果配置了 SMTP，检查发送记录"
echo "   - [ ] 如果有问题，更改 SMTP 密码"
echo ""

echo "8. Sentry"
echo "   控制台: https://sentry.io/ (或自托管实例)"
echo "   检查项:"
echo "   - [ ] 查看错误追踪记录"
echo "   - [ ] 检查是否有异常访问"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  📝 检查步骤                                              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "步骤 1: 逐个登录上述控制台"
echo "步骤 2: 检查 API Keys / Access Keys 列表"
echo "步骤 3: 查看调用日志和使用记录"
echo "步骤 4: 如果发现任何使用记录，立即撤销"
echo "步骤 5: 生成新的 API Keys（如果需要继续使用）"
echo "步骤 6: 更新 .env 文件（不要提交到 Git）"
echo "步骤 7: 重启应用"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ⚠️  紧急行动建议                                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo -e "${RED}今天必须完成：${NC}"
echo "1. 检查所有 AI 服务（DeepSeek, VolcEngine, Aliyun, OpenAI）"
echo "2. 检查 AWS S3（如果使用）"
echo "3. 撤销所有可疑的 API Keys"
echo "4. 清理 Git 历史并强制推送"
echo ""

echo -e "${YELLOW}本周完成：${NC}"
echo "1. 检查所有其他服务"
echo "2. 设置费用预警和使用上限"
echo "3. 启用 API 调用日志"
echo "4. 配置异常使用告警"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  📊 检查记录表                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "请记录检查结果："
echo ""
echo "DeepSeek: [ ] 已检查 | [ ] 无问题 | [ ] 已撤销旧 Key"
echo "VolcEngine: [ ] 已检查 | [ ] 无问题 | [ ] 已撤销旧 Key"
echo "Aliyun: [ ] 已检查 | [ ] 无问题 | [ ] 已撤销旧 Key"
echo "OpenAI: [ ] 已检查 | [ ] 无问题 | [ ] 已撤销旧 Key"
echo "AWS S3: [ ] 已检查 | [ ] 无问题 | [ ] 已撤销旧 Key"
echo "Bilibili: [ ] 已检查 | [ ] 无问题 | [ ] 已清除 Cookie"
echo "SMTP: [ ] 已检查 | [ ] 无问题 | [ ] 已更改密码"
echo "Sentry: [ ] 已检查 | [ ] 无问题 | [ ] 已更新配置"
echo ""

echo -e "${GREEN}✅ 完成检查后，请运行以下命令清理 Git 历史：${NC}"
echo ""
echo "./scripts/cleanup-git-history.sh"
echo "./scripts/verify-git-cleanup.sh"
echo "git push origin --force --all"
echo "git push origin --force --tags"
echo ""
