#!/bin/bash

# Sentry 自托管快速启动脚本
# 用于快速部署和配置本地 Sentry 实例

set -e

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Sentry 自托管快速启动脚本${NC}"
echo -e "${GREEN}========================================${NC}\n"

# 检查 Docker 和 Docker Compose
echo -e "${YELLOW}[1/7] 检查系统依赖...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}错误: 未找到 Docker，请先安装 Docker${NC}"
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}错误: 未找到 Docker Compose，请先安装 Docker Compose${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker 版本: $(docker --version)${NC}"
echo -e "${GREEN}✓ Docker Compose 版本: $(docker-compose --version)${NC}"

# 生成安全密钥
echo -e "\n${YELLOW}[2/7] 生成安全密钥...${NC}"

SENTRY_SECRET_KEY=$(openssl rand -base64 64 | tr -d '\n')
SENTRY_DB_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')

echo -e "${GREEN}✓ Sentry Secret Key: ${SENTRY_SECRET_KEY:0:20}...${NC}"
echo -e "${GREEN}✓ Database Password: ${SENTRY_DB_PASSWORD:0:20}...${NC}"

# 创建 Sentry 目录
echo -e "\n${YELLOW}[3/7] 创建 Sentry 目录...${NC}"

mkdir -p docker/sentry
cd docker/sentry

# 创建 .env 文件
echo -e "\n${YELLOW}[4/7] 配置环境变量...${NC}"

cat > .env <<EOF
# Sentry Self-Hosted Configuration
# Generated by setup-sentry.sh on $(date)

# Secret Key
SENTRY_SECRET_KEY="${SENTRY_SECRET_KEY}"

# URL Prefix
SENTRY_URL_PREFIX="http://localhost:9000"

# Server Email
SENTRY_SERVER_EMAIL="sentry@cmamsys.local"

# Database Configuration
SENTRY_DB_HOST="postgres"
SENTRY_DB_PORT="5432"
SENTRY_DB_NAME="sentry"
SENTRY_DB_USER="sentry"
SENTRY_DB_PASSWORD="${SENTRY_DB_PASSWORD}"

# Redis Configuration
SENTRY_REDIS_HOST="redis"
SENTRY_REDIS_PORT="6379"

# Email Configuration
SENTRY_EMAIL_HOST="smtp"
SENTRY_EMAIL_PORT="25"
SENTRY_EMAIL_USER=""
SENTRY_EMAIL_PASSWORD=""

# Logging Level
SENTRY_LOG_LEVEL="INFO"
EOF

echo -e "${GREEN}✓ 环境变量已保存到 docker/sentry/.env${NC}"

# 检查配置文件
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${RED}错误: 未找到 docker-compose.yml${NC}"
    exit 1
fi

if [ ! -f "sentry.conf.py" ]; then
    echo -e "${RED}错误: 未找到 sentry.conf.py${NC}"
    exit 1
fi

# 启动 Docker 服务
echo -e "\n${YELLOW}[5/7] 启动 Sentry 服务...${NC}"

docker-compose up -d

# 等待服务启动
echo -e "\n${YELLOW}等待服务启动...${NC}"
sleep 10

# 检查服务状态
if ! docker-compose ps | grep -q "Up"; then
    echo -e "${RED}错误: 服务启动失败${NC}"
    echo -e "${YELLOW}查看日志: docker-compose logs${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 所有服务已启动${NC}"

# 初始化数据库
echo -e "\n${YELLOW}[6/7] 初始化数据库...${NC}"

docker-compose run --rm web sentry db upgrade

# 创建管理员账户
echo -e "\n${YELLOW}创建管理员账户...${NC}"
echo -e "${YELLOW}请输入管理员邮箱和密码:${NC}"

read -p "管理员邮箱 [admin@cmamsys.local]: " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@cmamsys.local}

read -s -p "管理员密码: " ADMIN_PASSWORD
echo
read -s -p "确认密码: " ADMIN_PASSWORD_CONFIRM
echo

if [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD_CONFIRM" ]; then
    echo -e "${RED}错误: 密码不匹配${NC}"
    exit 1
fi

docker-compose run --rm web sentry createuser \
  --email "$ADMIN_EMAIL" \
  --password "$ADMIN_PASSWORD" \
  --superuser || true

echo -e "${GREEN}✓ 管理员账户已创建${NC}"

# 显示配置信息
echo -e "\n${YELLOW}[7/7] 完成！Sentry 配置信息:${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Sentry URL:       http://localhost:9000${NC}"
echo -e "${GREEN}管理员邮箱:       ${ADMIN_EMAIL}${NC}"
echo -e "${GREEN}管理员密码:       ******${NC}"
echo -e "${GREEN}========================================${NC}\n"

# 显示后续步骤
echo -e "${YELLOW}后续步骤:${NC}"
echo -e "1. 访问 http://localhost:9000 登录 Sentry"
echo -e "2. 创建组织和项目"
echo -e "3. 获取项目 DSN"
echo -e "4. 更新项目根目录的 .env 文件:"
echo -e "   SENTRY_DSN=\"<你的DSN>\""
echo -e "   NEXT_PUBLIC_SENTRY_DSN=\"<你的DSN>\""
echo -e "5. 重启 CMAMSys 应用"

echo -e "\n${YELLOW}常用命令:${NC}"
echo -e "查看日志:     cd docker/sentry && docker-compose logs -f"
echo -e "停止服务:     cd docker/sentry && docker-compose down"
echo -e "重启服务:     cd docker/sentry && docker-compose restart"
echo -e "备份数据库:   cd docker/sentry && docker-compose exec postgres pg_dump -U sentry sentry > backup.sql"

echo -e "\n${GREEN}✓ Sentry 自托管部署完成！${NC}\n"
