name: Test Docker

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker --version
          docker build -t test-image .
